# Generated by Django 2.0.7 on 2018-07-29 11:50

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=post.models.post_image, width_field='image_width'),
        ),
    ]
